apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amanydv860/nginx-gitops.git
    targetRevision: main
    path: charts/nginx
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://172.31.16.83:33893  
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
